# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

defaults: &defaults
  machine: true
  working_directory: ~/go/src/github.com/albertteoh/jaeger-go-example

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install tools
          command: |
            go install github.com/wadey/gocovmerge
            go install golang.org/x/lint/golint
            go install github.com/mjibson/esc
            go install github.com/securego/gosec/cmd/gosec
            go install honnef.co/go/tools/cmd/staticcheck
 
